language: go
sudo: false
go:
- 1.12.x
before_install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
env:
  global:
  - secure: Y3oi6IbzDkstdQcEe6pzFBIzEcpsX5GBmh4vQr/Q8ynZVReEDqD4kGVfAdaOxwjClOQIZHXtEq6S8Ad+SqHc41flohg8cMPDEqN5kZXUFehmSBgIPDiNg2mtXqLjCb3KGXAiaiv3uNzR8VAWZbWubpBDPHJraPWT1GmqwjLHIYRxOg1G+OrHZ/NTE383HZPLu33/N//w9QIN/59FBEWqYnyaO2FMBlf8c0oSFuQnmcb8eWjnRMIafNkKcXgmvAOnmsc+uHbBmmCj2eOmyWuA4XPj+Ds+yqLyCj+FA35ONPdcCOQVqanZS9OrHwviY3te+i2EkDSrXbyQFCdVuBF7HbYRVSVCxBp5eO4mwP4NuZgempiibgQiFMR8iAma1C/jMTAlDOIO7BFhVvLxlirNlVfPaXQ/r8hNaNnbCQVr8gA3kzmz2wxTCdAQ16RN1AMX6d4ODEGF3u4Dt6eNi1QAU09EAIcRBggMvNPfg+dSTvi43+lud14SFG995GWBEG8qUo7PacqhuFlhdwGBIYTm7mdsA1UCzyhtKvqr9e8Sic4ANkJcQ+4egl0YeFhLsH4LoN4Zf1xHAosMCPLzDQ5rYA0Nel8VjRVWjO6bI6LfduM+8iO4aB8nmxmqatC4cZtqZlTu4+sYeB26CUXF7sK2DyhCr/VyMnr5z4cPMNBO9h4=
script:
- "$GOPATH/bin/goveralls -service=travis-ci"
